### ISSUE TITLE
TypeError on substitution in the `Replacer`

### ISSUE THREAD

**Issue by derevnjuk** [NeuraLegion/har-sdk#66]
```
[2021-12-06T19:19:14.504] [ERROR] [TSED] - Error while capturing the HAR: TypeError: this.value.replace is not a function
at l.replace (/opt/services/node_modules/@har-sdk/postman/src/parser/Replacer.ts:22:29)
at c.parse (/opt/services/node_modules/@har-sdk/postman/src/parser/EnvVariableParser.ts:18:27)
at d.apiKeyAuth (/opt/services/node_modules/@har-sdk/postman/src/converter/DefaultConverter.ts:270:21)
at d.authRequest (/opt/services/node_modules/@har-sdk/postman/src/converter/DefaultConverter.ts:125:14)
at d.convertRequest (/opt/services/node_modules/@har-sdk/postman/src/converter/DefaultConverter.ts:101:14)
at reduce (/opt/services/node_modules/@har-sdk/postman/src/converter/DefaultConverter.ts:56:51)
at Array.reduce (<anonymous>)
at d.traverse (/opt/services/node_modules/@har-sdk/postman/src/converter/DefaultConverter.ts:48:24)
at reduce (/opt/services/node_modules/@har-sdk/postman/src/converter/DefaultConverter.ts:53:36)
at Array.reduce (<anonymous>)
at d.traverse (/opt/services/node_modules/@har-sdk/postman/src/converter/DefaultConverter.ts:48:24)
at reduce (/opt/services/node_modules/@har-sdk/postman/src/converter/DefaultConverter.ts:53:36)
at Array.reduce (<anonymous>)
```

**Comment by derevnjuk** [comment]
@pmstss perhaps, `ajv` skips some constraints for some reason or implicitly cast values to them. It might be an issue in some cases.

The validator returns no error for the following schema and data:

```json
"auth-attribute": {
  "type": "object",
  "title": "Auth",
  "description": "Represents an attribute for any authorization method provided by Postman. For example `username` and `password` are set as auth attributes for Basic Authentication method.",
  "properties": {
    "key": {
      "type": "string"
    },
    "value": {},
    "type": {
      "type": "string"
    }
  },
  "required": ["key"]
}
```

```json
"auth": {
  "type": "apikey",
  "apikey": [
    {
      "key": "key",
      "value": "Authorization",
      "type": "string"
    },
    {
      "key": "value",
      "value": true,
      "type": "boolean"
    },
    {
      "key": "in",
      "value": "header",
      "type": "string"
    }
  ]
},
```

Wdyt?

**Comment by pmstss** [comment]
@derevnjuk but which constrains are skipped above? looks like npe is caused by calling `replace()` on boolean (`true`) which is valid value by schema

**Comment by derevnjuk** [comment]
@pmstss omg, I mislooked at the definition. I didn't notice that `type` is missed.
